Решение задач 1, 2, 3  Занятие 1: Основы JavaScript
js-tasks-ru/jsbasic-20210114_rainur pull request #2
Opened 2021-01-17 20:01 UTC by rainurka

2021-01-17 20:08 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Вычислить факториал
+ факториал 1 равен 1
+ факториал 3 равен 6 
+ факториал 5 равен 120 
+ факториал 0 равен 1
```
```diff
Сделать первый символ заглавным
+ должна работать для пустой строки
+ должна работать для строки из одной буквы
+ должна делать первый символ заглавным
```
```diff
Допишите функцию валидации имени пользователя
+ если имя корректное, то true
+ если содержит пробелы, то false
+ если меньше 4 символов то false
+ если null то false
```

Добавляю преподавателя (@stas-dolgachov) для код-ревью, посмотрим что он скажет :)

2021-01-18 08:37 UTC, stas-dolgachov requested changes

2021-01-18 08:37 UTC, stas-dolgachov commented on 1-module/1-task/index.js
> +  result=1;
Переменные обязательно объявлять, если вы используете их внутри функции. Добавьте, пожалуйста, let здесь.

2021-01-18 08:37 UTC, stas-dolgachov commented on 1-module/2-task/index.js
> +    return true
Для if и else желательно всегда использовать фигурные скобочки, это позволяет избежать ошибок, если кода становится больше.

2021-01-18 08:37 UTC, stas-dolgachov commented on 1-module/3-task/index.js
> +  result="";
Тоже самое с let здесь.

2021-01-18 20:14 UTC, closed without merging

2021-01-18 20:15 UTC, rainurka commented
Закрою этот и добавляю новый с решением всех 5-и задач